name: mattboldt.com
github_username: mattboldt
highlighter: rouge
permalink: /:title/
year: 2017
description: Matt Boldt
url: http://www.mattboldt.com
encoding: UTF-8


kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
sass:
  sass_dir: ./assets/css

paginate: 7
paginate_path: /page/:num/